services:

  db:
    container_name: ${COMPOSE_PROJECT_NAME}_db
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=app
      - MYSQL_USER=app
      - MYSQL_PASSWORD=app
      - TZ=Europe/Zurich
    volumes:
      - db-data:/var/lib/mysql

  php:
    container_name: ${COMPOSE_PROJECT_NAME}_php
    build:
      context: ./docker
      dockerfile: build/php.Dockerfile
    environment:
      - SSH_AUTH_SOCK=/run/host-services/ssh-auth.sock
    volumes:
      - './:/app'
      - ./docker/map/php.custom.ini:/usr/local/etc/php/conf.d/zzz-custom.ini:ro
      - /run/host-services/ssh-auth.sock:/run/host-services/ssh-auth.sock
    depends_on:
      - db

  nginx:
    container_name: ${COMPOSE_PROJECT_NAME}_nginx
    image: nginx:stable-alpine
    ports:
      - 8001:80
    volumes:
      - './:/app'
      - ./docker/map/nginx.default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php

  phpmyadmin:
    container_name: ${COMPOSE_PROJECT_NAME}_phpmyadmin
    image: phpmyadmin:latest
    restart: always
    ports:
      - "8210:80"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=app
      - PMA_USER=root
      - PMA_PASSWORD=root
      - PMA_ARBITRARY=1
    depends_on:
      - db


volumes:
  db-data:
